[package]
name = "whimsy"
version = "0.1.0"
authors = ["Cedric Hutchings <cedhut02@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustpython-vm = { git = "https://github.com/RustPython/RustPython.git" }
rustpython-compiler = { git = "https://github.com/RustPython/RustPython.git" }
quicksilver = { git = "https://github.com/cedric-h/quicksilver.git" }
num-traits = "0.2.11"
fxhash = "0.2.1"
